version: '3.8'
services: 
  salon_inv:
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - 8001:8000

  inv_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: inv_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
