version: '3.8'
services: 
  salon_auth:
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - 8000:8000

  auth_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
